name: Integration
on:
  push: # On every push on any branch
jobs:
  Build: # Job name
    runs-on: ubuntu-latest # Operating system selection
    steps:
      - name: Checkout # custom name Checkout the repository
        uses: actions/checkout@v4 # Action implemented in this repository, tag "2"
      - name: Setup Java
        uses: actions/setup-java@v4
        with: # Actions parameters (action name omitted)
          java-version: 19
          distribution: temurin
      - name: Build
        run: ./gradlew build